#!/usr/bin/env bash

# 配置 config.toml 设置 esc 执行 脚本 切换英文
# 使用 `ibus engine xkb:us:eng` 在 wayland 下出现不一致问题
# gnome 下需要插件, d-bus send
# https://github.com/kevinhwang91/gnome-shell-ibus-switcher

# 获取当前的输入法
cmd_read_im="dbus-send --session --type=method_call --print-reply=literal --dest=org.gnome.Shell /org/gnome/Shell/Extensions/IbusSwitcher org.gnome.Shell.Extensions.IbusSwitcher.CurrentSource"

im=$(eval "$cmd_read_im" | awk -F "|" '{print $2}')

# 检查是否为英文, 这里用的是 rime, 根据自己的 ibus 处理
if [ "$im" != "A" ]; then
    cmd_switch_ibus_a="dbus-send --session --type=method_call --print-reply=literal --dest=org.gnome.Shell /org/gnome/Shell/Extensions/IbusSwitcher org.gnome.Shell.Extensions.IbusSwitcher.SwitchSource uint32:1 string:A"
    eval "$cmd_switch_ibus_a"
fi


# switch en   0|
# dbus-send --session --type=method_call --print-reply=literal --dest=org.gnome.Shell /org/gnome/Shell/Extensions/IbusSwitcher org.gnome.Shell.Extensions.IbusSwitcher.SwitchSource uint32:0 string:

# swich rime 1:小, 1:A 英文
# dbus-send --session --type=method_call --print-reply=literal --dest=org.gnome.Shell /org/gnome/Shell/Extensions/IbusSwitcher org.gnome.Shell.Extensions.IbusSwitcher.SwitchSource uint32:1 string:小
