theme = "onelight_local"

[editor]
# auto-info = true 显示操作提示信息,默认true
# line-number = "relative"  # 行号类型 absolute / relative 
# rulers = [80, 120]   # 标尺

# 真彩支持
# 使用 infocmp | rg color 检查是否支持 256color [终端控制命令 infocmp](http://manual.51yip.com/shell/terminalccmds.html) 
# 使用 tmux 的时候,追加配置  
# set -g default-terminal "tmux-256color" 
# set -ga terminal-overrides ',xterm-256color:Tc' 
# 需要 export TERM=xterm-256color  
# tty export COLORTERM=truecolor
true-color = true

# 支持 diagnostics, line-numbers, spacer, diff
#gutters = ["diagnostics", "diff", "line-numbers","spacer"] 

auto-completion = true
cursorline = true
color-modes = true
idle-timeout = 40
auto-save = true
auto-info = true
# line-number = "relative"

# bufferline show buffer at top 
# set  always, multiple, nerver
# bufferline = "nerver" 


[editor.soft-wrap]
enable = true
max-wrap = 25 # increase value to reduce forced mid-word wrapping
max-indent-retain = 0
wrap-indicator = ""  # set wrap-indicator to "" to hide it

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
# 服务器语言信息提示 
display-messages = true
# display-signature-help-docs = false
# LSP Type Hints default is false
# display-inlay-hints = true 

# [editor.whitespace]
# render = "all"

# all / none
[editor.whitespace.render]
space = "all"
tab = "all"
newline = "all"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
tab = "→"
newline = "⏎"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "╎", "┆", "┊"

# 状态栏定义
[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "file-name", "file-modification-indicator"] 
center = ["diagnostics","workspace-diagnostics"]
right = [ "selections", "position", "position-percentage", "file-encoding", "file-line-ending", "file-type", ]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

#[6118]
[editor.sticky-context]
enable = true
# indicator = true
max-lines = 0

[keys.normal]
# use `li` or remap `after insert`
a = ["move_char_right","insert_mode"]
"C-s" = ":write"  # 原保存跳转列表位置，修改为 C-j
"C-j" = ["save_selection"]
"C-r" = ":reload"
"C-z" = "normal_mode"     # replace suspend
"C-q" = ":quit"
"A-/" = "toggle_comments"
"\\" = ":reflow" # |
"X" = "extend_line_above"
"Z" = { "Z" = [":quit"] }

# macos 自动切换到英文环境
"esc" = [":sh macism com.apple.keylayout.ABC", "normal_mode"]

# space mode
[keys.normal.space]
"x" = ":buffer-close"
"w" = { "r" = ":config-reload" }
"." = "file_picker_in_current_buffer_directory"

[keys.insert]
"esc" = [":sh macism com.apple.keylayout.ABC", "normal_mode"]

# [keys.select]
