# Author : Gokul Soumya <gokulps15@gmail.com>

# modifiers bold italic underlined  dim reversed

"attribute" = { fg = "yellow" }
"comment" = { fg = "light-gray", modifiers = ["italic"] }
# "comment" = { fg = "light-gray", modifiers = [] }
"constant" = { fg = "cyan" }
"constant.numeric" = { fg = "gold" }
"constant.builtin" = { fg = "gold" }
"constant.character.escape" = { fg = "gold" }

"constructor" = { fg = "blue" }

"function" = { fg = "blue" }
"function.builtin" = { fg = "cyan" }
"function.macro" = { fg = "purple" }

"keyword" = { fg = "purple" }
"keyword.function" = { fg = "purple" }
"keyword.control" = { fg = "purple" }
"keyword.control.import" = { fg = "red" }
"keyword.directive" = { fg = "purple" }
"keyword.operator" = { fg = "purple" }
"keyword.storage.type" = { fg = "purple" }

"tag" = "yellow"
"label" = { fg = "purple" }
"namespace" = { fg = "blue" }
"operator" = { fg = "purple" }
"property" = { fg = "red" }
"special" = { fg = "blue" }
"string" = { fg = "green" }

"type" = { fg = "yellow" }
"type.builtin" = "blue"
# "variable" = { fg = "blue" }

"variable.builtin" = { fg = "blue" }
"variable.parameter" = { fg = "red" }
"variable.other.member" = { fg = "red" }

"markup.heading" = { fg = "red" }
"markup.raw.inline" = { fg = "green" }
"markup.bold" = { fg = "gold", modifiers = ["bold"] }
"markup.italic" = { fg = "purple", modifiers = ["italic"] }
"markup.list" = { fg = "red" }
"markup.quote" = { fg = "yellow" }
"markup.link.url" = { fg = "cyan", modifiers = ["underlined"]}
"markup.link.text" = { fg = "purple" }
"markup.heading.1" = { fg = "red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "gold", modifiers = ["bold"] }
"markup.heading.3" = { fg = "yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "green", modifiers = ["bold"] }
"markup.heading.5" = { fg = "blue", modifiers = ["bold"] }
"markup.heading.6" = { fg = "black", modifiers = ["bold"] }

"diff.plus" = "green"
"diff.delta" = "gold"
"diff.minus" = "red"

"diagnostic" = { modifiers = ["underlined"] }
# dev: undercurled
"diagnostic.info" = { modifiers = ["undercurled"] }
"diagnostic.hint" = { modifiers = ["underlined"] }
"diagnostic.warning" = { modifiers = ["underlined"] }
"diagnostic.error" = { modifiers = ["undercurled"] }
"info" = { fg = "blue", modifiers = ["bold"] }
"hint" = { fg = "green", modifiers = ["bold"] }
"warning" = { fg = "yellow", modifiers = ["bold"] }
"error" = { fg = "red", modifiers = ["bold"] }

"ui.background" = { bg = "black" }
"ui.virtual" = { fg = "faint-gray" }
"ui.virtual.indent-guide" = { fg = "light-gray" }
"ui.virtual.whitespace" = { fg = "faint-gray" }
"ui.virtual.ruler" = { bg = "gray" }

"ui.cursor" = { fg = "black", bg="white" }
"ui.cursor.primary" = { fg = "black", bg = "white" }
"ui.cursor.match" = { fg = "blue", modifiers = ["underlined"]}

"ui.selection" = { bg = "light-gray" }
"ui.selection.primary" = { bg = "gray" }
"ui.cursorline.primary" = { bg = "light-black" }

"ui.linenr" = { fg = "linenr" }
"ui.linenr.selected" = { fg = "white" }

"ui.statusline" = { fg = "white", bg = "light-black" }
"ui.statusline.inactive" = { fg = "light-gray", bg = "light-black" }
"ui.statusline.normal" = { fg = "light-black", bg = "blue" }
"ui.statusline.insert" = { fg = "light-black", bg = "green" }
"ui.statusline.select" = { fg = "light-black", bg = "purple" }

"ui.text" = { fg = "white" }
"ui.text.focus" = { fg = "white", bg = "light-black", modifiers = ["bold"] }

"ui.help" = { bg = "gray" }
"ui.popup" = { bg = "gray" }
"ui.window" = { bg = "black" }
"ui.menu" = { fg = "white", bg = "gray" }
"ui.menu.selected" = { fg = "black", bg = "blue" }

[palette]

yellow = "#E5C07B"
blue = "#61AFEF"
red = "#E06C75"
purple = "#C678DD"
green = "#98C379"
gold = "#D19A66"
cyan = "#56B6C2"
white = "#ABB2BF"
black = "#282C34"
light-black = "#2C323C"
gray = "#3E4452"
faint-gray = "#3B4048"
light-gray = "#5C6370"
linenr = "#4B5263"
